### ISSUE TITLE
Why did you decide to migrate from Go to C++?

### ISSUE THREAD

**Issue by t4wE** [AbyssEngine/AbyssEngineOld#135]
Just wondering.

Was it performance issues or C/C++ interop?

Thanks.

**Comment by essial** [comment]
CGO. The performance of calling native (non go) libraries from golang is garbage slow, especially when dealing with high performance things such as graphics rendering. That may or may not have changed since the switch, but at the time, we were spending weeks tracking out severe performance issues that always seemed to lead back to CGO.

**Comment by t4wE** [comment]
Thanks, that's what I thought. I experienced the same issue in my projects.

There are new languages compatible with C popping up. I'm now writing my game in V (https://vlang.io), it's basically Go but with C interop, performance, and some nice additions like sum types and better error handling.
